---
galaxy_info:
  author: "Benno Joy, Martin Verges"
  company: "AnsibleWorks, First Colo GmbH"
  license: "Simplified BSD License"
  min_ansible_version: 1.9
  platforms:
  - name: Debian
    versions:
      - wheezy
      - jessie
  - name: Ubuntu
    versions:
      - precise
      - quantal
      - raring
      - saucy
      - trusty
      - utopic
      - vivid
  - name: EL
  categories:
    - networking
    - system
dependencies: []
