---
dependencies: []

galaxy_info:
  author: alexclear
  description: 'Scrit to disable selinux.'
  license: "license (BSD, MIT)"
  min_ansible_version: 1.6
  platforms:
  - name: EL
    versions:
    - all
  categories:
    - networking
    - system
    - web
